name:                HaskellBook
version:             0.1.0.0
github:              "arthurborisow/HaskellBook"
license:             BSD3
author:              "Arthur Borisow"
copyright:           "2020 Arthur Borisow"

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src
  ghc-options:
    - -Wall
  dependencies:
    - time
    - QuickCheck
    - checkers
    - random
    - transformers
    - trifecta
executables:
  HaskellBook-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -Wall
    - -Wincomplete-uni-patterns
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - HaskellBook

tests:
  HaskellBook-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - HaskellBook
    - hspec
    - QuickCheck
